services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - question-network
  
  question:
    container_name: question
    image: question
    build:
      context: services/question
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      DB_CLOUD_URI: ${QUESTION_DB_CLOUD_URI}
      DB_LOCAL_URI: ${QUESTION_DB_LOCAL_URI}
      DB_USERNAME: ${QUESTION_DB_USERNAME}
      DB_PASSWORD: ${QUESTION_DB_PASSWORD}
    volumes:
      - /app/node_modules
      - ./services/question:/app
    networks:
      - question-network
      - question-db-network

  question-db:
    container_name: question-db
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${HISTORY_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${HISTORY_DB_PASSWORD}
    volumes:
      - question-db:/data/db
    networks:
      - question-db-network
  
  history:
    container_name: history
    image: history
    build:
      context: services/history
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      DB_CLOUD_URI: ${HISTORY_DB_CLOUD_URI}
      DB_LOCAL_URI: ${HISTORY_DB_LOCAL_URI}
      DB_USERNAME: ${HISTORY_DB_USERNAME}
      DB_PASSWORD: ${HISTORY_DB_PASSWORD}
    volumes:
      - /app/node_modules
      - ./services/history:/app
    networks:
      - history-network
      - history-db-network

  history-db:
    container_name: history-db
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${QUESTION_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${QUESTION_DB_PASSWORD}
    volumes:
      - history-db:/data/db
    networks:
      - history-db-network

volumes:
  question-db:
  history-db:

networks:
  question-network:
    driver: bridge
  question-db-network:
    driver: bridge
  history-network:
    driver: bridge
  history-db-network:
    driver: bridge